[update-version] Detect errors.
[From SVN r7066 (trunk)]

diff --git a/update-version b/update-version
--- a/update-version
+++ b/update-version
@@ -2,6 +2,9 @@
 
 set -e
 
+LC_ALL=C
+export LC_ALL
+
 if [ $# -lt 3 ] || [ $# -gt 5 ]; then
   echo >&2 "Usage: $0 <major> <minor> <patchlevel> [ <suffix> [ - ] ]"
   echo >&2 "(use 5 arguments to produce patches for releases)"
@@ -14,23 +17,37 @@ fi
 #   ./update-version 2 3 0
 #   ./update-version 2 3 0 p1 -
 
+replace()
+{
+  if [ ! -h "$2" ] && [ -r "$2" ] && [ -w "$2" ]; then
+    err=`perl -pi -e "$1" "$2" 2>&1 >/dev/null`
+    if [ -n "$err" ]; then
+      printf >&2 "Error from perl:\n%s\n" "$err"
+      exit 2
+    fi
+  else
+    printf >&2 "Error: %s is not a readable/writable file\n" "$2"
+    exit 2
+  fi
+}
+
 vers="$1.$2.$3"
 full="$vers${4:+-$4}"
 echo $full > VERSION
-perl -pi -e "s/(?<=#define MPFR_VERSION_MAJOR ).*/$1/; \
-             s/(?<=#define MPFR_VERSION_MINOR ).*/$2/; \
-             s/(?<=#define MPFR_VERSION_PATCHLEVEL ).*/$3/; \
-             s/(?<=#define MPFR_VERSION_STRING ).*/\"$full\"/" mpfr.h
-perl -pi -e "s/(?<=return \").*\"/$full\"/" version.c
+replace "s/(?<=#define MPFR_VERSION_MAJOR ).*/$1/; \
+         s/(?<=#define MPFR_VERSION_MINOR ).*/$2/; \
+         s/(?<=#define MPFR_VERSION_PATCHLEVEL ).*/$3/; \
+         s/(?<=#define MPFR_VERSION_STRING ).*/\"$full\"/" mpfr.h
+replace "s/(?<=return \").*\"/$full\"/" version.c
 
 if [ $# -lt 5 ]; then
   # Up to 4 arguments...
   u="http://www.mpfr.org/mpfr-"
-  perl -pi -e "s/(?<=\@set VERSION ).*/$full/" mpfr.texi
-  perl -pi -e \
+  replace "s/(?<=\@set VERSION ).*/$full/" mpfr.texi
+  replace \
     "s,MPFR [\d.]+( web page \@url{$u)[\d.]+/,MPFR $vers\${1}$vers/," mpfr.texi
-  perl -pi -e "s/(?<=AC_INIT).*/([MPFR],[$full])/" configure.in
-  perl -pi -e "s,(?<=$u).*?/,$vers/," INSTALL
+  replace "s/(?<=AC_INIT).*/([MPFR],[$full])/" configure.in
+  replace "s,(?<=$u).*?/,$vers/," INSTALL
 fi
 
 echo "MPFR version successfully updated."
