[tools/ck-mparam] Also check the mparam.h files with check_mparam.c.
[From SVN r12531 (trunk)]

diff --git a/tools/ck-mparam b/tools/ck-mparam
--- a/tools/ck-mparam
+++ b/tools/ck-mparam
@@ -3,7 +3,7 @@
 # Check the mparam.h files. This script is useful as not all mparam.h
 # files may be tested by our tests.
 
-# Copyright 2011 Free Software Foundation, Inc.
+# Copyright 2011-2018 Free Software Foundation, Inc.
 # This script is free software; the Free Software Foundation
 # gives unlimited permission to copy and/or distribute it,
 # with or without modifications, as long as this notice is preserved.
@@ -12,6 +12,8 @@
 # but WITHOUT ANY WARRANTY, to the extent permitted by law; without
 # even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 # PARTICULAR PURPOSE.
+
+set -e
 
 # ck-mparam can be run from the tools directory
 dir=`pwd`
@@ -23,9 +25,14 @@ err=0
 for i in $files
 do
   output=`echo "#include \"$i\"" | gcc -o /dev/null -c -xc - 2>&1`
-  [ -z "$output" ] && continue
-  printf "Error for file '%s':\n%s\n" "$i" "$output"
-  err=1
+  if [ -n "$output" ]; then
+    printf "Error for file '%s':\n%s\n" "$i" "$output"
+    err=1
+  fi
+  rm -f check_mparam
+  gcc "-DMPARAM=\"../$i\"" -o check_mparam tools/check_mparam.c
+  ./check_mparam
+  rm -f check_mparam
 done
 
 exit $err
